const assert = require("assert");
const fs = require("fs");
const path = require("path");

const backendRoot = path.resolve(__dirname, "..");
const baseSql = fs.readFileSync(
    path.join(backendRoot, "supabase", "000_base_schema.sql"),
    "utf8"
);
const stageSql = fs.readFileSync(
    path.join(backendRoot, "supabase", "012_multitenant_foundation.sql"),
    "utf8"
);
const finalizeSql = fs.readFileSync(
    path.join(backendRoot, "supabase", "013_multitenant_finalize.sql"),
    "utf8"
);
const backgroundJobLeaseSql = fs.readFileSync(
    path.join(backendRoot, "supabase", "014_background_job_leases.sql"),
    "utf8"
);
const recurringJobGuardSql = fs.readFileSync(
    path.join(
        backendRoot,
        "supabase",
        "015_recurring_background_job_guard.sql"
    ),
    "utf8"
);
const diaryTenantWindowSql = fs.readFileSync(
    path.join(
        backendRoot,
        "supabase",
        "016_diary_tenant_source_window.sql"
    ),
    "utf8"
);
const localNotificationInstallationSql = fs.readFileSync(
    path.join(
        backendRoot,
        "supabase",
        "017_local_notification_installations.sql"
    ),
    "utf8"
);
const nurserySql = fs.readFileSync(
    path.join(backendRoot, "supabase", "023_nursery.sql"),
    "utf8"
);
const accountRuntimeStateSql = fs.readFileSync(
    path.join(
        backendRoot,
        "supabase",
        "026_account_runtime_state.sql"
    ),
    "utf8"
);
const rehearsal = fs.readFileSync(
    path.join(backendRoot, "scripts", "rehearse-multitenant-migration.ps1"),
    "utf8"
);

for (const table of [
    "user_profiles",
    "companions",
    "companion_profile_versions",
    "stable_memory_candidates",
    "media_assets",
    "push_installations",
    "background_jobs",
    "delivery_events"
]) {
    assert.match(stageSql, new RegExp(`public\\.${table}\\b`));
}

for (const baseTable of ["settings", "conversations", "memories", "messages"]) {
    assert.match(
        baseSql,
        new RegExp(`create table if not exists public\\.${baseTable}`)
    );
}
assert.match(baseSql, /id bigint generated by default as identity primary key/);

for (const legacyTable of [
    "settings",
    "conversations",
    "memories",
    "messages",
    "moments",
    "moment_comments",
    "companion_diary_entries",
    "mcp_connections",
    "ai_provider_profiles"
]) {
    assert.match(
        stageSql,
        new RegExp(`alter table if exists public\\.${legacyTable}`)
    );
    assert.match(finalizeSql, new RegExp(`'${legacyTable}'`));
}

assert.match(stageSql, /finalize_legacy_owner_migration/);
assert.match(stageSql, /email_confirmed_at is not null/);
assert.match(stageSql, /legacy_owner_migration_blocked/);
assert.match(
    stageSql,
    /where \(user_id is null\) <> \(companion_id is null\)/i
);
assert.match(
    stageSql,
    /messages_tenant_client_message_uidx[\s\S]*user_id,\s*companion_id,\s*client_message_id/i
);
assert.match(
    stageSql,
    /messages_staged_client_message_uidx[\s\S]*user_id is null or companion_id is null/i
);
assert.match(
    stageSql,
    /function public\.claim_chat_generation\([\s\S]*p_user_id uuid[\s\S]*p_companion_id uuid/i
);
assert.match(
    stageSql,
    /insert into public\.messages\s*\(\s*user_id,\s*companion_id,\s*conversation_id/i
);
assert.match(stageSql, /message_id bigint/);
assert.match(stageSql, /reply_to_message_id bigint references public\.messages\(id\)/);
assert.doesNotMatch(stageSql, /\bmessage_id\s+uuid\b/);
assert.doesNotMatch(stageSql, /reply_to_message_id uuid/);
assert.match(stageSql, /revoke all on function public\.finalize_legacy_owner_migration/);
assert.match(stageSql, /to service_role/);
assert.doesNotMatch(
    stageSql,
    /grant execute on function public\.finalize_legacy_owner_migration\(uuid\)\s+to authenticated/
);
assert.match(finalizeSql, /tenant_finalize_blocked/);
assert.match(finalizeSql, /alter column user_id set not null/);
assert.match(finalizeSql, /foreign key \(user_id, companion_id\)/);
assert.match(
    finalizeSql,
    /drop function if exists public\.claim_chat_generation\(uuid, uuid, integer\)/i
);
assert.match(
    finalizeSql,
    /drop function if exists public\.commit_chat_generation_reply\(uuid, uuid, text, jsonb, boolean\)/i
);
assert.match(stageSql, /dedupe_key text not null/);
assert.match(stageSql, /lease_expires_at timestamptz/);
assert.match(stageSql, /update storage\.buckets\s+set public = false\s+where id = 'moments'/);
assert.match(
    stageSql,
    /create policy %I on public\.%I for select to authenticated/
);
assert.match(stageSql, /grant select on table public\.messages to authenticated/);
for (const internalTable of [
    "media_assets",
    "background_jobs",
    "delivery_events",
    "push_installations"
]) {
    assert.match(
        stageSql,
        new RegExp(
            `revoke all on table public\\.${internalTable} from anon, authenticated`
        )
    );
}
assert.match(rehearsal, /Production database modified: false/);
assert.match(rehearsal, /restore into an isolated Supabase project before production/);
for (const functionName of [
    "claim_background_jobs",
    "renew_background_job_lease",
    "complete_background_job",
    "fail_background_job"
]) {
    assert.match(
        backgroundJobLeaseSql,
        new RegExp(`function public\\.${functionName}\\b`, "i")
    );
}
assert.match(backgroundJobLeaseSql, /for update skip locked/i);
assert.match(
    backgroundJobLeaseSql,
    /grant execute on function public\.claim_background_jobs[\s\S]*to service_role/i
);
assert.doesNotMatch(
    backgroundJobLeaseSql,
    /grant execute on function public\.claim_background_jobs[\s\S]*to authenticated/i
);
assert.match(
    recurringJobGuardSql,
    /create unique index if not exists background_jobs_recurring_pending_uidx/i
);
assert.match(
    recurringJobGuardSql,
    /where status = 'pending'[\s\S]*?'proactive_message'[\s\S]*?'diary_update'/i
);
assert.match(
    diaryTenantWindowSql,
    /drop index if exists public\.companion_diary_source_window_uidx/i
);
assert.match(
    diaryTenantWindowSql,
    /create unique index if not exists companion_diary_tenant_source_window_uidx[\s\S]*user_id,\s*companion_id,\s*source_window_end/i
);
assert.match(
    localNotificationInstallationSql,
    /provider in \('jpush', 'getui', 'local_poll'\)/i
);
for (const table of [
    "nursery_children",
    "nursery_child_state",
    "nursery_actions",
    "nursery_corpus",
    "nursery_utterances",
    "nursery_events",
    "nursery_milestones",
    "nursery_caregiver_bonds"
]) {
    assert.match(nurserySql, new RegExp(`public\\.${table}\\b`));
    assert.match(
        nurserySql,
        new RegExp(`revoke all on table public\\.${table}`)
    );
}
assert.match(
    nurserySql,
    /foreign key \(user_id, companion_id, child_id\)[\s\S]*references public\.nursery_children\(user_id, companion_id, id\)/i
);
assert.match(nurserySql, /job_type = 'nursery_event'/i);
assert.match(nurserySql, /where status in \('active', 'runaway'\)/i);
assert.match(
    localNotificationInstallationSql,
    /token_hash text/i
);
assert.match(
    localNotificationInstallationSql,
    /foreign key \(user_id, companion_id\)[\s\S]*references public\.companions\(user_id, id\)/i
);
assert.match(
    localNotificationInstallationSql,
    /push_installations_local_token_uidx[\s\S]*token_hash/i
);
assert.match(
    accountRuntimeStateSql,
    /create table if not exists public\.companion_runtime_states/i
);
assert.match(
    accountRuntimeStateSql,
    /primary key \(user_id, companion_id\)/i
);
assert.match(
    accountRuntimeStateSql,
    /foreign key \(user_id, companion_id\)[\s\S]*references public\.companions\(user_id, id\)/i
);
assert.match(
    accountRuntimeStateSql,
    /revoke all on table public\.companion_runtime_states[\s\S]*anon, authenticated/i
);

console.log("multi-tenant staged migration contract tests passed");
