-- DengTa Home reproducible base schema.
--
-- The production project originally created these four tables through the
-- dashboard. Keeping their idempotent definitions here makes a clean restore
-- possible before the incremental migrations are applied.

create table if not exists public.settings (
    id uuid primary key default gen_random_uuid(),
    ai_name text not null default '小灯',
    system_prompt text not null default '',
    personality text not null default '',
    provider text not null default 'custom',
    api_url text not null default '',
    model text not null default '',
    temperature numeric not null default 0.7,
    context_turns integer not null default 20,
    max_tokens integer not null default 2048,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    compression_threshold integer not null default 40,
    compression_keep integer not null default 20,
    timezone text not null default 'Asia/Shanghai',
    push_enabled boolean not null default false,
    max_push_per_day integer not null default 7
);

create table if not exists public.conversations (
    id uuid primary key default gen_random_uuid(),
    title text not null default '新对话',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.memories (
    id uuid primary key default gen_random_uuid(),
    conversation_id uuid references public.conversations(id)
        on delete cascade,
    summary text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.messages (
    id bigint generated by default as identity primary key,
    conversation_id uuid not null references public.conversations(id)
        on delete cascade,
    role text not null,
    content text not null,
    created_at timestamptz not null default now(),
    visible boolean not null default true
);

create index if not exists conversations_updated_at_idx
    on public.conversations (updated_at desc);
create index if not exists messages_conversation_created_idx
    on public.messages (conversation_id, created_at);
create index if not exists memories_conversation_updated_idx
    on public.memories (conversation_id, updated_at desc);

alter table public.settings enable row level security;
alter table public.conversations enable row level security;
alter table public.memories enable row level security;
alter table public.messages enable row level security;

revoke all on table public.settings from anon, authenticated;
revoke all on table public.conversations from anon, authenticated;
revoke all on table public.memories from anon, authenticated;
revoke all on table public.messages from anon, authenticated;
grant all on table public.settings to service_role;
grant all on table public.conversations to service_role;
grant all on table public.memories to service_role;
grant all on table public.messages to service_role;
