-- DengTa Home: tenant-private zero-provider nursery.

create table if not exists public.nursery_children (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null,
    companion_id uuid not null,
    name text check (
        name is null or char_length(name) between 1 and 20
    ),
    status text not null default 'active'
        check (status in ('active', 'runaway', 'graduated')),
    born_at timestamptz not null default now(),
    paused_at timestamptz,
    total_paused_seconds bigint not null default 0
        check (total_paused_seconds >= 0),
    stage_policy_version smallint not null default 1,
    rng_seed bigint not null,
    state_version bigint not null default 0
        check (state_version >= 0),
    celebrated_stage text,
    runaway_at timestamptz,
    ending text,
    appearance text not null default '',
    birth_action_id text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    foreign key (user_id, companion_id)
        references public.companions(user_id, id) on delete cascade,
    unique (user_id, companion_id, id),
    unique (user_id, companion_id, birth_action_id)
);

create unique index if not exists nursery_one_current_child_uidx
    on public.nursery_children (user_id, companion_id)
    where status in ('active', 'runaway');

create table if not exists public.nursery_child_state (
    user_id uuid not null,
    companion_id uuid not null,
    child_id uuid not null,
    mood numeric not null default 70 check (mood between 0 and 100),
    health numeric not null default 85 check (health between 0 and 100),
    intimacy numeric not null default 20 check (intimacy between 0 and 100),
    nutrition numeric not null default 65 check (nutrition between 0 and 100),
    fatigue numeric not null default 20 check (fatigue between 0 and 100),
    darkness numeric not null default 0 check (darkness between 0 and 100),
    digest_load numeric not null default 0 check (digest_load between 0 and 100),
    last_settled_at timestamptz not null default now(),
    last_fed_at timestamptz,
    last_interaction_at timestamptz,
    updated_at timestamptz not null default now(),
    primary key (user_id, companion_id, child_id),
    foreign key (user_id, companion_id, child_id)
        references public.nursery_children(user_id, companion_id, id)
        on delete cascade
);

create table if not exists public.nursery_actions (
    id uuid primary key,
    user_id uuid not null,
    companion_id uuid not null,
    child_id uuid not null,
    actor text not null check (actor in ('user', 'companion', 'system')),
    kind text not null check (kind in (
        'birth', 'name', 'feed', 'soothe', 'diaper', 'burp',
        'play', 'teach', 'talk', 'discipline', 'event'
    )),
    payload jsonb not null default '{}'::jsonb,
    idempotency_key text not null,
    state_version_before bigint not null default 0,
    state_version_after bigint not null default 0,
    effective_at timestamptz not null default now(),
    applied_at timestamptz,
    created_at timestamptz not null default now(),
    foreign key (user_id, companion_id, child_id)
        references public.nursery_children(user_id, companion_id, id)
        on delete cascade,
    unique (user_id, companion_id, child_id, idempotency_key)
);

create index if not exists nursery_actions_recent_idx
    on public.nursery_actions (
        user_id,
        companion_id,
        child_id,
        effective_at desc
    );

create table if not exists public.nursery_corpus (
    id bigint generated by default as identity primary key,
    user_id uuid not null,
    companion_id uuid not null,
    child_id uuid not null,
    source_kind text not null default 'direct'
        check (source_kind in (
            'direct', 'night', 'book', 'conversation_opt_in', 'system'
        )),
    source_message_id bigint,
    speaker text not null check (speaker in ('user', 'companion', 'system')),
    text text not null check (char_length(text) between 1 and 1000),
    content_sha256 text not null,
    char_count integer not null check (char_count between 1 and 1000),
    training_weight numeric not null default 1
        check (training_weight between 0.05 and 2),
    scene text not null default 'home',
    created_at timestamptz not null default now(),
    foreign key (user_id, companion_id, child_id)
        references public.nursery_children(user_id, companion_id, id)
        on delete cascade,
    unique (user_id, companion_id, child_id, content_sha256)
);

create index if not exists nursery_corpus_recent_idx
    on public.nursery_corpus (
        user_id,
        companion_id,
        child_id,
        id desc
    );

create table if not exists public.nursery_utterances (
    id bigint generated by default as identity primary key,
    user_id uuid not null,
    companion_id uuid not null,
    child_id uuid not null,
    trigger text not null default 'action',
    stage text not null,
    text text not null check (char_length(text) between 1 and 160),
    generation_parameters jsonb not null default '{}'::jsonb,
    accepted boolean not null default true,
    rejection_reason text,
    created_at timestamptz not null default now(),
    foreign key (user_id, companion_id, child_id)
        references public.nursery_children(user_id, companion_id, id)
        on delete cascade
);

create index if not exists nursery_utterances_recent_idx
    on public.nursery_utterances (
        user_id,
        companion_id,
        child_id,
        created_at desc
    );

create table if not exists public.nursery_events (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null,
    companion_id uuid not null,
    child_id uuid not null,
    kind text not null,
    due_at timestamptz,
    expires_at timestamptz,
    status text not null default 'pending'
        check (status in ('pending', 'fired', 'expired', 'cancelled')),
    payload jsonb not null default '{}'::jsonb,
    dedupe_key text not null,
    created_at timestamptz not null default now(),
    fired_at timestamptz,
    foreign key (user_id, companion_id, child_id)
        references public.nursery_children(user_id, companion_id, id)
        on delete cascade,
    unique (user_id, companion_id, child_id, dedupe_key)
);

create table if not exists public.nursery_milestones (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null,
    companion_id uuid not null,
    child_id uuid not null,
    kind text not null,
    title text not null,
    note text not null default '',
    source_utterance_id bigint references public.nursery_utterances(id)
        on delete set null,
    dedupe_key text not null,
    created_at timestamptz not null default now(),
    pinned_at timestamptz,
    foreign key (user_id, companion_id, child_id)
        references public.nursery_children(user_id, companion_id, id)
        on delete cascade,
    unique (user_id, companion_id, child_id, dedupe_key)
);

create table if not exists public.nursery_caregiver_bonds (
    user_id uuid not null,
    companion_id uuid not null,
    child_id uuid not null,
    caregiver_kind text not null check (caregiver_kind in ('user', 'companion')),
    attachment numeric not null default 20 check (attachment between 0 and 100),
    trust numeric not null default 20 check (trust between 0 and 100),
    predictability numeric not null default 20 check (predictability between 0 and 100),
    resentment numeric not null default 0 check (resentment between 0 and 100),
    updated_at timestamptz not null default now(),
    primary key (user_id, companion_id, child_id, caregiver_kind),
    foreign key (user_id, companion_id, child_id)
        references public.nursery_children(user_id, companion_id, id)
        on delete cascade
);

alter table public.background_jobs
    drop constraint if exists background_jobs_job_type_check;
alter table public.background_jobs
    add constraint background_jobs_job_type_check check (
        job_type in (
            'proactive_message',
            'moment_post',
            'moment_interaction',
            'diary_update',
            'profile_refresh',
            'creative_check',
            'surprise_reveal',
            'nursery_event'
        )
    );

create unique index if not exists background_jobs_nursery_pending_uidx
    on public.background_jobs (user_id, companion_id, dedupe_key)
    where status = 'pending' and job_type = 'nursery_event';

alter table public.nursery_children enable row level security;
alter table public.nursery_child_state enable row level security;
alter table public.nursery_actions enable row level security;
alter table public.nursery_corpus enable row level security;
alter table public.nursery_utterances enable row level security;
alter table public.nursery_events enable row level security;
alter table public.nursery_milestones enable row level security;
alter table public.nursery_caregiver_bonds enable row level security;

revoke all on table public.nursery_children from anon, authenticated;
revoke all on table public.nursery_child_state from anon, authenticated;
revoke all on table public.nursery_actions from anon, authenticated;
revoke all on table public.nursery_corpus from anon, authenticated;
revoke all on table public.nursery_utterances from anon, authenticated;
revoke all on table public.nursery_events from anon, authenticated;
revoke all on table public.nursery_milestones from anon, authenticated;
revoke all on table public.nursery_caregiver_bonds from anon, authenticated;

grant all on table public.nursery_children to service_role;
grant all on table public.nursery_child_state to service_role;
grant all on table public.nursery_actions to service_role;
grant all on table public.nursery_corpus to service_role;
grant all on table public.nursery_utterances to service_role;
grant all on table public.nursery_events to service_role;
grant all on table public.nursery_milestones to service_role;
grant all on table public.nursery_caregiver_bonds to service_role;

comment on table public.nursery_corpus is
    'Tenant-private, explicitly supplied text used only by the local child language learner.';
comment on table public.nursery_children is
    'One current zero-provider nursery child per user and companion pair.';
